### ISSUE TITLE
release FunctionMesh helm charts independently

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh#356]

**Comment by tpiperatgod** [comment]
We would like to make the helm chart releasing process for [function-mesh-operator](https://github.com/streamnative/charts/tree/master/charts/function-mesh-operator) independent from the [streamnative/charts](https://github.com/streamnative/charts) repository, as the [helm chart](https://github.com/streamnative/function-mesh/tree/master/charts/function-mesh-operator) in the [streamnative/function-mesh](https://github.com/streamnative/function-mesh) repository will be more active. To achieve this, we have the following TODOs:

- [x] Add `branch-0.1` branch for releasing
- [x] Add `gh-pages` branch for host "charts.functionmesh.io" #363 
- [x] Migrate and update `.ci/release.sh` & `.ci/git.sh` from `streamnative/charts` repository (on `master` and `branch-0.1`) #364 #367 
- [ ] Upgrade "chart-releaser" to **v1.2.0** (on `master` and `branch-0.1`) #369 #370 
- [ ] Add a new workflow for auto releasing the helm chart of the function-mesh-operator [#1874](https://github.com/streamnative/streamnative-ci/pull/1874) [#1880](https://github.com/streamnative/streamnative-ci/pull/1880)
- [ ] Create a new organization called "FunctionMesh" (or something like that) on [artifacthub.io](https://artifacthub.io/) and maintain the "chats.functionmesh.io" index
- [ ] Clean up the deprecated [function-mesh-operator](https://artifacthub.io/packages/helm/streamnative/function-mesh-operator) chart under the StreamNative organization on [artifacthub.io](https://artifacthub.io/)

**Comment by freeznet** [comment]
Since we will having a two-weeks grace period (19th May ~ 2nd June) to let our user migrate from https://github.com/streamnative/charts/tree/master/charts/function-mesh-operator to https://github.com/streamnative/function-mesh/tree/master/charts/function-mesh-operator. @Huanli-Meng could you please help @tpiperatgod to work on the docs part, thanks.
I have listed some of the action items:
- [ ] function mesh website [install-function-mesh-through-helm](https://functionmesh.io/docs/install-function-mesh#install-function-mesh-through-helm)
- [ ] streamnative platform [step-1-install-streamnative-platform](https://docs.streamnative.io/platform/latest/quickstart#step-1-install-streamnative-platform)

**Comment by tpiperatgod** [comment]
How should we deal with the [documentation](https://github.com/streamnative/function-mesh/tree/master/charts/function-mesh-operator) in the streamnative/charts repo?

I suggest we keep it and then align the section in the top-level documentation about installing Function Mesh with the latest documentation for Function Mesh.

**Comment by freeznet** [comment]
https://github.com/streamnative/charts/pull/734 removes the original helm chart, and close this issue.
